name: Create pull request
description:  Create a pull request 
author: Marius Mihalcea

inputs:
  token:
    description: the validation token
    required: true
  owner:
    description: the name of the owner/org where this repo is created
    required: true
  repo:
    description: the name of the repository
    required: true
  base-branch:
    description: the name of the branch where you have the changes
    required: true
  head-branch:
    description: the name of the branch where you want merge the changes
    required: true
  title:
    description: the title of the pull request
    required: false
  body:
    description: the content mesage of the pull request
    required: false
  modify:
    description: indicate whether the maintainer can modify the pull request
    required: false
    default: "true"
  assignees:
    description: the username of the persons that will be assigne to this PR
    required: false
    default: ${{ github.actor }}
  reviewers:
    description: the username of the persons you want to add as reviewers
    required: false
  team-reviewers: 
      description: the slug of the teams you want to add as reviewers
      required: false
runs:
  using: "composite"
  steps:
    - name: Run Bash script on Linux
      if: runner.os == 'Linux'
      run: ${{ github.workspace }}/create-pull-request/script.sh
      shell: bash

    - name: Run PowerShell script on Windows
      if: runner.os == 'Windows'
      run: |
        ${{ github.workspace }}/create-pull-request/createPullRequest.ps1 `
          -token '${{ inputs.token }}' `
          -owner '${{ inputs.owner }}' `
          -repo '${{ inputs.repo }}' `
          -baseBranch '${{ inputs.base-branch }}'' `
          -headBranch '${{ inputs.head-branch }}' `
          -title '${{ inputs.title }}' `
          -body '${{ inputs.body }}' `
          -modify '${{ inputs.modify }}' `
          -assignees [${{ inputs.assignees }}] `
          -reviewers [${{ inputs.reviewers }}' `
          -teamReviewers [${{ inputs.team-reviewers }}]'
      shell: pwsh
