name: Create Bugfix Branch and PR

on:
  workflow_dispatch:
    inputs:
        Ticket_ID:
            description: 'Ticket number'
            required: true
            type: string

jobs:
  create-bugfix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create bugfix branch
      run: |
        BRANCH_NAME="bugfix/${{ inputs.Ticket_ID }}-Create-files"
        git checkout -b "$BRANCH_NAME"
        git push --set-upstream origin "$BRANCH_NAME"

    - name: Create some changes
      run: ./make-files.sh
    
    - name: Configure Git user as workflow actor
      run: |
        git config --local user.name "${{ github.actor }}"
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Commit and push
      run: |
        git add -A
        git commit -m "Add files"
        git push
